Add some guidance for ACK scheduling
quicwg/multipath pull request #129
Opened 2022-07-07 13:21 UTC by qdeconinck

Fixes #123.

2022-07-08 11:33 UTC, Yanmei-Liu commented on draft-ietf-quic-multipath.md
> +periodically send ACK(_MP) frames on the path they acknowledge packets.
Sending ACK_(MP) frames on the fastest path is one of the ACK scheduling strategies, but IMO the most common strategy is sending ACK_(MP) frames on the same path of the packet was sent. By the way, as QUIC-TRANSPORT doesn't contain a mechanism to calculate one-way-delay on a certain path, it's very important that we need to add some guidance for one-way-delay calculation(e.g. [QUIC-Timestamp]) with the fastest path ACK scheduling strategy, and some guidance for the potential impact on congestion control.

2022-07-08 11:35 UTC, Yanmei-Liu requested changes
Need to add guidance for one-way-delay calculation and impact on congestion control, if we want to recommend the fastest path ACK scheduling strategy.

2022-07-11 10:48 UTC, Yanmei-Liu approved these changes

2022-07-11 12:24 UTC, mirjak commented
I believe we can merge this now as it is. If we want to add more guidance later we should open a separate issue and another PR.

2022-07-11 12:30 UTC, merged