Send Abandon frame after NAT rebinding
quicwg/multipath pull request #198
Opened 2023-03-10 14:57 UTC by mirjak

This is the proposed text more the other PR to start working this. The proposed solution in further discussion was to also extend the path abandon path with a specific reason code of this case.

2023-03-10 15:22 UTC, mirjak commented
See issue #188

2023-03-10 17:03 UTC, huitema requested changes
That PR is premature. We do not yet have consensus on how to solve issue #188, and we should keep the discussion there.

2023-03-10 17:21 UTC, mirjak commented
Yes, this is not ready to merge and discuss should take place in the issue (#188). I just wanted to capture this text as a starting point before we lose it.

2024-02-20 05:54 UTC, huitema commented
I think we need clarity on PR #292 before we progress this draft. We have an issue there, because the "Natted" path and the "before-NAT" path use the same number space. With PR #292, that gives us a strong constraint. I think I explained a plausible solution in https://github.com/quicwg/multipath/pull/292#discussion_r1493966132, but with that solution if rebinding is accepted the new (natted) path will have the same path_id as before NAT rebinding.

2024-05-27 14:50 UTC, mirjak commented
OBE after merge of #292

2024-05-27 14:50 UTC, closed without merging