PATH_STANDBY/AVAILABLE can be sent for all issued DCIDs
quicwg/multipath pull request #277
Opened 2023-10-20 09:56 UTC by mirjak

fixes #272

2023-10-20 09:57 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +A PATH_STANDY may be bundled with a NEW_CONNECTION_ID frame or
```suggestion
A PATH_STANDY MAY be bundled with a NEW_CONNECTION_ID frame or
```

2023-10-20 09:57 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +A PATH_AVAILABLE may be bundled with a NEW_CONNECTION_ID frame or
```suggestion
A PATH_AVAILABLE MAY be bundled with a NEW_CONNECTION_ID frame or
```

2023-10-20 12:12 UTC, Yanmei-Liu approved these changes

2023-10-20 14:02 UTC, qdeconinck requested changes
Mostly typos.

2023-10-20 14:02 UTC, qdeconinck commented on draft-ietf-quic-multipath.md
> +  MAY be used even if a path was not initated yet.
```suggestion
  MAY be used even if it is not yet in user over a path.
```

2023-10-20 14:02 UTC, qdeconinck commented on draft-ietf-quic-multipath.md
> +A PATH_STANDY MAY be bundled with a NEW_CONNECTION_ID frame or
```suggestion
A PATH_STANDBY frame MAY be bundled with a NEW_CONNECTION_ID frame or
```

2023-10-20 14:02 UTC, qdeconinck commented on draft-ietf-quic-multipath.md
> +PATH_RESPONSE frame in order to indicated the prefered path usage
```suggestion
PATH_RESPONSE frame in order to indicate the preferred path usage
```

2023-10-20 14:02 UTC, qdeconinck commented on draft-ietf-quic-multipath.md
> +  MAY be used even if a path was not initated yet.
```suggestion
  MAY be used even if it is not yet in user over a path.
```

2023-10-20 14:02 UTC, qdeconinck commented on draft-ietf-quic-multipath.md
> +A PATH_AVAILABLE MAY be bundled with a NEW_CONNECTION_ID frame or
```suggestion
A PATH_AVAILABLE frame MAY be bundled with a NEW_CONNECTION_ID frame or
```

2023-10-20 14:02 UTC, qdeconinck commented on draft-ietf-quic-multipath.md
> +PATH_RESPONSE frame in order to indicated the prefered path usage
```suggestion
PATH_RESPONSE frame in order to indicate the preferred path usage
```

2023-10-21 09:59 UTC, kazuho reviewed
Thank you for the PR.

Looks good modulo editorial preferences.

2023-10-21 09:59 UTC, kazuho commented on draft-ietf-quic-multipath.md
> +  MAY be used even if a path was not initated yet.
```suggestion
  MAY be specified even if it is not yet in use over a path.
```
"specified" in addition to @qdeconinck's suggestions.

2023-10-21 09:59 UTC, kazuho commented on draft-ietf-quic-multipath.md
> +  MAY be used even if a path was not initated yet.
```suggestion
  MAY be specified even if it is not yet in use over a path.
```

2023-10-22 00:23 UTC, huitema approved these changes
This is fine. On one hand, it forces the implementers to remember available/standby status per CID, on the other hand, it suppresses a race condition. Since we already have to maintain sequence number state per CID, this is an acceptable tradeoff.

2023-10-22 07:54 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +PATH_RESPONSE frame in order to indicate the preferred path usage
Do we need to also mention PATH_CHALLENGE?

2023-10-22 08:02 UTC, yfmascgy reviewed
Some minor changes

2023-10-22 08:04 UTC, yfmascgy reviewed
Looks good to me. Some minor changes.

2023-10-22 09:47 UTC, merged