Add MAX_PATH_ID_BLOCKED frame and related texts
quicwg/multipath pull request #402
Opened 2024-07-02 08:47 UTC by yfmascgy

This is an attempt to fix issue #342. I have added the MAX_PATH_ID_BLOCKED frame and related texts. Note that the same Path ID is used in both directions to address a path so the path identifier can be either limited by the sender or its peer. We should treat the two scenario differently and MAX_PATH_ID_BLOCKED should be used when the limit is set by the peer.

2024-07-02 09:28 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +
```suggestion
```

2024-07-02 09:30 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +be treated as a connection error of type MP_PROTOCOL_VIOLATION.
```suggestion
: A variable-length integer indicating the maximum number of path identifiers
  allowed at the time the frame was sent. This value MUST NOT exceed 2^32-1
  and MUST NOT be lower than the value advertised in the initial_max_path_id
  transport parameter. Receipt of an invalid Maximum Path Identifier value MUST
  be treated as a connection error of type MP_PROTOCOL_VIOLATION.
```

2024-07-02 09:35 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +but the limit of active paths set by the peer has been reached.
PR #386 removes this sentence here as we should only specify it once in the doc.

2024-07-02 19:45 UTC, huitema approved these changes
makes sense. Minor nit.

2024-07-03 16:01 UTC, Yanmei-Liu approved these changes
Looks good.

2024-07-04 10:33 UTC, mirjak commented on draft-ietf-quic-multipath.md
This is the same text we already have for the MAX_PATHS frame.

2024-07-10 14:59 UTC, gloinul commented on draft-ietf-quic-multipath.md
> +indicates that the limit of active paths set by the peer has been reached.
should it be stated that it is an request to the peer to consider increasing it?

2024-07-10 14:59 UTC, gloinul commented on draft-ietf-quic-multipath.md
I would agree that "invalid" is a bit unclear. Higher than so far declared is fairly obvious. But is closed path ID invalid, they could just be in the process to be closed.

2024-09-02 15:23 UTC, mirjak requested changes
These changes requests change the name to PATHS_BLOCKED as discussed at IETF-120.

2024-09-02 15:23 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +active paths, while MAX_PATH_ID_BLOCKED frame (see {{max-paths-blocked-frame}})
```suggestion
active paths, while PATHS_BLOCKED frame (see {{max-paths-blocked-frame}})
```

2024-09-02 15:23 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +(when limited by the sender) or a MAX_PATH_ID_BLOCKED frame
```suggestion
(when limited by the sender) or a PATHS_BLOCKED frame
```

2024-09-02 15:23 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +MAX_PATH_ID_BLOCKED frames are formatted as shown in {{fig-max-paths-blocked-frame-format}}.
```suggestion
PATHS_BLOCKED frames are formatted as shown in {{fig-max-paths-blocked-frame-format}}.
```

2024-09-02 15:23 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +MAX_PATH_ID_BLOCKED Frame {
```suggestion
PATHS_BLOCKED Frame {
```

2024-09-02 15:23 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +## MAX_PATH_ID_BLOCKED frames {#max-paths-blocked-frame}
```suggestion
## PATHS_BLOCKED frames {#paths-blocked-frame}
```

2024-09-02 15:23 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +(see Section {{max-paths-blocked-frame}}) to inform the peer that a new path
```suggestion
(see Section {{paths-blocked-frame}}) to inform the peer that a new path
```

2024-09-02 15:23 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +A sender SHOULD send a MAX_PATH_ID_BLOCKED frame (type=0x15228c0d) when
```suggestion
A sender SHOULD send a PATHS_BLOCKED frame (type=0x15228c0d) when
```

2024-09-02 15:23 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +MAX_PATH_ID frames contain the following field:
```suggestion
PATHS_BLOCKED frames contain the following field:
```

2024-09-02 15:23 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +TBD-08 (experiments use 0x15228c0d)                  | MAX_PATH_ID_BLOCKED    | {{max-paths-blocked-frame}}
```suggestion
TBD-08 (experiments use 0x15228c0d)                  | PATHS_BLOCKED    | {{max-paths-blocked-frame}}
```

2024-09-03 01:20 UTC, huitema reviewed
I merged Mirja's suggestion, because that simplifies further reviews. I still have a doubt about treating some variants as invalid. The "blocked" frames are largely informational, they do not compel the peer to take action, so the fewer side effects the better.

2024-09-03 01:20 UTC, huitema commented on draft-ietf-quic-multipath.md
My concern is that implementers might consider the PATHS_BLOCKED frame invalid if they have already sent a MAX_PATH_ID with a larger value. Then we get into splitting hair, "lower than initial value is invalid, but lower than current limit is just fine." Might be simpler to say that this frame is ignored with no action if the maximum path identifier parameter is lower than the largest maximum path ID advertised by the receiver.

2024-09-03 16:30 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +indicates that the limit of active paths set by the peer has been reached.
```suggestion
active paths, and PATHS_BLOCKED frame (see {{paths-blocked-frame}})
to notify the peer of being blocked to open new paths as
the limit of active paths set by the peer has been reached.
```
Is that any better/more accurate?

2024-09-03 16:31 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +indicates that the limit of active paths set by the peer has been reached.
@gloinul @MikeBishop can you check my proposal above?

2024-09-03 16:35 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +  be treated as a connection error of type MP_PROTOCOL_VIOLATION.
```suggestion
: A variable-length integer indicating the maximum path identifiers that was
  allowed at the time the frame was sent. If the received value is lower than
  the currently allowed maximum value, this frame can be ignored.
  Receipt of a value that is larger than the Maximum Path Identifier value MUST
  be treated as a connection error of type PROTOCOL_VIOLATION.
```

2024-09-03 16:38 UTC, mirjak commented on draft-ietf-quic-multipath.md
okay, yes the text was actually not correct as the max limit should be the current max value. a higher value raised an error. However a lower value can just be ignore. Also with the current version of the doc the field carries the max value and not the max number. Please review my proposed update above! @gloinul @huitema @MikeBishop

2024-09-16 14:14 UTC, qdeconinck approved these changes

2024-09-16 14:25 UTC, merged