Describe the effect of disable_active_migration more accurately
quicwg/multipath pull request #403
Opened 2024-07-02 15:03 UTC by Yanmei-Liu

Solving issue #343

2024-07-04 10:22 UTC, mirjak commented on draft-ietf-quic-multipath.md
> +to establish new paths for the peer address used during handshake,
```suggestion
to establish new paths to the same peer address as used during handshake,
```

2024-07-04 10:26 UTC, mirjak commented
This PR is fine but I propose to not merge it now but have some discussion at the meeting first. The use case for this as explained in issue #343 is anycast but I would like to double-check that there are no other reasons that would limit the opening of new paths before the preferred server address is used.

2024-07-17 20:31 UTC, MikeBishop requested changes

2024-07-17 20:31 UTC, MikeBishop commented on draft-ietf-quic-multipath.md
> +If endpoint receives a disable_active_migration transport parameter
```suggestion
If an endpoint receives a disable_active_migration transport parameter
```

2024-07-17 20:31 UTC, MikeBishop commented on draft-ietf-quic-multipath.md
> +but establishment of additional paths to other peer addresses
```suggestion
to establish new paths to the peer's handshake address. However,
establishment of additional paths from any local address to other peer addresses
```

I think we need to state that this TP also doesn't restrict the endpoint to a single local address.

2024-09-02 14:35 UTC, merged