PATH_ACK can still be sent after PATH_ABANDON
quicwg/multipath pull request #456
Opened 2024-10-31 16:45 UTC by mirjak

2024-11-05 00:07 UTC, huitema requested changes
This is the wrong fix. The root cause is that the text in the last paragraph of "PATH_ABANDON Frame" section contradicts the specification in "Path Close". It should be replaced by a simple reference, e.g. "The use of the PATH_ABANDON frame to close paths is specified in section {{path-close}}."

2024-11-05 14:18 UTC, mirjak commented
@huitema agreed. Done!

2024-11-05 15:34 UTC, Yanmei-Liu approved these changes

2024-11-05 15:40 UTC, qdeconinck approved these changes

2024-11-13 13:25 UTC, gloinul approved these changes

2024-11-18 04:46 UTC, Yanmei-Liu approved these changes

2024-11-18 04:46 UTC, merged