High level overview
quicwg/multipath pull request #88
Opened 2022-01-12 16:59 UTC by obonaventure

Here is an attempt to provide a high level overview that summarizes the main principles of multipath QUIC. This should be expanded as we improve the text to align it with the full extension.

2022-01-20 08:44 UTC, yfmascgy reviewed
This overview puts a lot of emphasis on the algorithm side. I understand those algorithms eventually are integral parts if we want to make multipath quic work. But I feel this is a bit out of the scope of this very first draft. Maybe we should revisit this later on.

2022-03-03 16:50 UTC, mirjak commented on draft-lmbdhk-quic-multipath.md
> +A multipath QUIC connection starts with a QUIC handshake as a regular QUIC connection.
```suggestion
A multipath QUIC connection starts with a QUIC handshake as a regular QUIC connection.
See further Section {{nego}}.
```

2022-03-03 16:51 UTC, mirjak commented on draft-lmbdhk-quic-multipath.md
> +the chosen path. In this version of the document, a QUIC server does not initiate the creation
```suggestion
the chosen path, as further described in Section {{setup}}.
In this version of the document, a QUIC server does not initiate the creation
```

2022-03-03 18:55 UTC, huitema requested changes
Please make it shorter...

2022-03-03 18:55 UTC, huitema commented on draft-lmbdhk-quic-multipath.md
> +that can be used during a connection. A multipath QUIC connection is thus an established QUIC
The active_connection_id_limit transport parameter *binds* the maximum number of paths

2022-03-03 18:55 UTC, huitema commented on draft-lmbdhk-quic-multipath.md
> +that can be used during a connection. A multipath QUIC connection is thus an established QUIC
The active CID limits binds the number of simultaneous paths. Or in fact, the number of simultaneous number spaces. It does not bind the total number of paths. When a path is abandoned, the CID is retired, the peer provides a new CID, and that new CID can be used on a new path.

2022-03-03 18:55 UTC, huitema commented on draft-lmbdhk-quic-multipath.md
> +
I agree with Mirja that this is a bit too detailed, probably too long. The path creation and packet scheduling functions are local functions defined by the implementation. We cannot really standardize what implementations do, so the best is to just have a mention that these functions exist, and leave it at that.

2022-03-03 19:14 UTC, mirjak requested changes

2022-03-03 19:14 UTC, mirjak commented on draft-lmbdhk-quic-multipath.md
> +The active_connection_id_limit transport parameter bounds the maximum number of paths
```suggestion
The active_connection_id_limit transport parameter limits the maximum number of active paths
```

2022-03-04 14:18 UTC, qdeconinck reviewed
While the first part of the overview looks good, the second one is probably too detailed. I made some suggestions to simplify it.

2022-03-04 14:18 UTC, qdeconinck commented on draft-lmbdhk-quic-multipath.md
> +create additional paths if the existing path becomes congested.
I agree. I will try to rephrase this.

2022-03-04 14:18 UTC, qdeconinck commented on draft-lmbdhk-quic-multipath.md
> +
With the shortened version, I think the above paragraph can be moved in another PR that could indeed be placed in the scheduling section.

2022-03-04 15:09 UTC, mirjak commented on draft-lmbdhk-quic-multipath.md
> +
@qdeconinck can you create a new PR?

2022-03-07 09:21 UTC, closed without merging

2022-03-07 09:21 UTC, qdeconinck commented
Followed up by #108.