transport parameter in RFC9000 are unchanged
quicwg/multipath pull request #99
Opened 2022-03-03 18:58 UTC by mirjak

resolves #91

2022-03-03 19:29 UTC, huitema approved these changes

2022-03-04 10:57 UTC, obonaventure requested changes
There are two parts in this PR.

First, the following sentences:

This extension does not change the definition of any transport parameter
defined in {{Section 18.2. of QUIC-TRANSPORT}}. 
Inline with the definition in {{QUIC-TRANSPORT}} disable_active_migration
also disables multipath support, except "after a client has acted on a
preferred_address transport parameter" {{Section 18.2. of QUIC-TRANSPORT}}.

These sentences are at the right place. I would replace "any" by "all the" but that's a detail.

For the second part, I think that we should solve this problem differently. The current text is the following:

Further, it is out of scope for
this document if the old address can also be used for multipath
after a client has migrated to the address provided in the preferred_address
transport parameter. However, it SHOULD NOT be assumed that it is
possible to use both addresses simultaneously without further confirmation
from the other host.

I would suggest to discuss somewhere in the document how the client learns the server address and how preferred address is used. Since we do not have a way for the server to convey the list of "multipath-capable" addresses in this document, I would suggest a simple approach:
- When preferred address is not used, then the client can only establish multipath flows to the server address
- When preferred address is used, then if a client migrates to one of the preferred addresses according to 9.6 of RFC9000, then it must consider this address as the endpoint of all multipath flows

I guess that we'll need to define later a transport parameter that provides the list of "multipath-capable" addresses of a given server. In the mean time, we should opt for a simple solution.

2022-03-04 11:07 UTC, mirjak commented
@obonaventure you wrote:

> When preferred address is not used, then the client can only establish multipath flows to the server address
> When preferred address is used, then if a client migrates to one of the preferred addresses according to 9.6 of RFC9000, then it must consider this address as the endpoint of all multipath flows

That sounds like you want to restrict the multipath extension to only one server address (but potentially different paths from different clients address)...?

I think this restriction is unnecessary. Yes we don't specify a way to learn server addresses but that doesn't means that the client doesn't know (e.g. based on higher layer information) multiple addresses of the server. What should we restrict that?

2022-03-04 11:08 UTC, mirjak commented
However, can we maybe merge this PR as it is for now and you open a separate issue for your additional point @obonaventure ?

2022-03-04 12:45 UTC, qdeconinck approved these changes
The proposed PR sounds good to me, with the slight addition I mentioned.

2022-03-04 12:45 UTC, qdeconinck commented on draft-ietf-quic-multipath.md
> +this document if the old address can also be used for multipath
```suggestion
this document to specify if the old address can also be used for multipath
```

2022-03-04 12:56 UTC, Yanmei-Liu approved these changes

2022-03-04 17:03 UTC, obonaventure commented
Mirja,

> > When preferred address is not used, then the client can only establish multipath flows to the server address
> > When preferred address is used, then if a client migrates to one of the preferred addresses according to 9.6 of RFC9000, then it must consider this address as the endpoint of all multipath flows
> 
> That sounds like you want to restrict the multipath extension to only one server address (but potentially different paths from different clients address)...?

That was my understanding of the sentences in the PR. Maybe I got it wrong.

> 
> I think this restriction is unnecessary. Yes we don't specify a way to learn server addresses but that doesn't means that the client doesn't know (e.g. based on higher layer information) multiple addresses of the server. What should we restrict that?

I think that we should discuss the role of preferred address in section 3 where we explain how paths can be opened.

2022-03-04 17:04 UTC, obonaventure commented
> However, can we maybe merge this PR as it is for now and you open a separate issue for your additional point @obonaventure ?

Fine, let's do it this way.

2022-03-04 17:05 UTC, obonaventure approved these changes

2022-03-06 04:06 UTC, yfmascgy approved these changes

2022-03-07 04:25 UTC, merged